#!/usr/bin/env python3
"""
LibreOffice-based document converter for single file conversion
"""

import subprocess
import tempfile
import shutil
import logging
from pathlib import Path

# Get logger instance
logger = logging.getLogger(__name__)


def get_libreoffice_command():
    """Get the correct LibreOffice command for the current system"""
    # Common LibreOffice command paths
    possible_commands = [
        'soffice',  # Standard Linux/Docker
        'libreoffice',  # Alternative Linux
        '/Applications/LibreOffice.app/Contents/MacOS/soffice',  # macOS
        '/usr/bin/soffice',  # Linux system install
        '/opt/libreoffice/program/soffice',  # Alternative Linux path
    ]
    
    for cmd in possible_commands:
        try:
            result = subprocess.run([cmd, '--version'], 
                                  capture_output=True, text=True, timeout=10)
            if result.returncode == 0:
                return cmd
        except (subprocess.TimeoutExpired, FileNotFoundError):
            continue
    
    return None


def check_libreoffice_available():
    """Check if LibreOffice is available on the system"""
    return get_libreoffice_command() is not None


def convert_single_file_libreoffice(input_file, output_file=None):
    """
    Convert a single document file to PDF using LibreOffice
    
    Args:
        input_file (str): Path to input document file
        output_file (str, optional): Path for output PDF file
        
    Returns:
        str: Path to the created PDF file, or None if conversion failed
    """
    input_path = Path(input_file).resolve()
    
    if not input_path.exists():
        raise FileNotFoundError(f"Input file not found: {input_file}")
    
    if input_path.suffix.lower() not in ['.docx', '.doc', '.odt', '.rtf']:
        raise ValueError(f"Unsupported file format: {input_path.suffix}")
    
    # Check if LibreOffice is available
    libreoffice_cmd = get_libreoffice_command()
    if not libreoffice_cmd:
        raise RuntimeError("LibreOffice is not available. Please install LibreOffice.")
    
    # Determine output file path
    if output_file:
        output_path = Path(output_file).resolve()
    else:
        output_path = input_path.with_suffix('.pdf')
    
    # Create temporary directory for conversion
    with tempfile.TemporaryDirectory() as temp_dir:
        try:
            # Convert using LibreOffice headless mode
            cmd = [
                libreoffice_cmd,
                '--headless',
                '--invisible',
                '--nodefault',
                '--nolockcheck',
                '--nologo',
                '--norestore',
                '--convert-to', 'pdf',
                '--outdir', temp_dir,
                str(input_path)
            ]
            
            # Log the actual command being executed
            logger.info(f"Executing LibreOffice command: {' '.join(cmd)}")
            
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
            
            logger.info(f"LibreOffice return code: {result.returncode}")
            logger.debug(f"LibreOffice stdout: {result.stdout}")
            if result.stderr:
                logger.warning(f"LibreOffice stderr: {result.stderr}")
            
            if result.returncode != 0:
                raise RuntimeError(f"LibreOffice conversion failed with code {result.returncode}: {result.stderr}")
            
            # Find the generated PDF file
            temp_pdf = Path(temp_dir) / f"{input_path.stem}.pdf"
            
            logger.debug(f"Looking for PDF at: {temp_pdf}")
            logger.debug(f"Files in LibreOffice temp directory: {list(Path(temp_dir).iterdir())}")
            
            if not temp_pdf.exists():
                raise RuntimeError(f"PDF file was not generated by LibreOffice. Expected: {temp_pdf}")
            
            logger.info(f"Moving PDF from {temp_pdf} to {output_path}")
            
            # Ensure output directory exists
            output_path.parent.mkdir(parents=True, exist_ok=True)
            
            # Move the PDF to the desired location
            shutil.move(str(temp_pdf), str(output_path))
            
            logger.info(f"Successfully created PDF at: {output_path}")
            logger.info(f"Final PDF file exists: {output_path.exists()}")
            logger.info(f"Final PDF file size: {output_path.stat().st_size if output_path.exists() else 'N/A'} bytes")
            
            return str(output_path)
            
        except subprocess.TimeoutExpired:
            raise RuntimeError("LibreOffice conversion timed out after 60 seconds")
        except Exception as e:
            raise RuntimeError(f"LibreOffice conversion error: {str(e)}")
